### ISSUE TITLE
Error on uninstall of pysilfont 1.1.2

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/pysilfont#15]
I'm trying to uninstall pysilfont in order to reinstall it and get this error:

```
macbookpro-7299:font-nokyung victor$ sudo -H pip uninstall pysilfont
Password:
Uninstalling pysilfont-1.1.2:
  /Library/Python/2.7/site-packages/pysilfont-1.1.2-py2.7.egg
  /usr/local/bin/ftmlcreateodt
  /usr/local/bin/ufoconvert
  /usr/local/bin/ufosyncmeta
Proceed (y/n)? y
  Successfully uninstalled pysilfont-1.1.2
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Library/Python/2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Library/Python/2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/pysilfont-1.1.2-py2.7.egg'

```

**Comment by DavidRaymond** [comment]
Odd that the error comes after the "Successfully uninstalled message".  Will investigate along with other installation issues.

**Comment by nrsiward** [comment]
Perhaps pip notices the egg doesn't exist so concludes the state that should exist after uninstall does already exist but then calls an operation that looks for the egg (assuming the egg really is not there).

**Comment by DavidRaymond** [comment]
It appears that this error can be ignored, and we've documented this in README.md.

Do we need to do more?

**Comment by nrsiward** [comment]
I don't think so. I'm closing this issue.
