### ISSUE TITLE
UFObuildComp: Uncaught exception if advance width is a floating point number

### ISSUE THREAD

**Issue by madig** [silnrsi/pysilfont#23]
1. Extract [test.zip](https://github.com/silnrsi/pysilfont/files/1050360/test.zip)
2. Do:
```
$ cat > composite.txt
i = dotlessi + dotaccentcomb@top
$ UFObuildComp -i composite.txt test.ufo/
```
Backtrace: 
```
2017-06-04 15:48:44 Progress: Opening log file for output: test_CD.log
2017-06-04 15:48:44 Progress: Opening file for input: composite.txt
2017-06-04 15:48:44 Progress: Reading UFO: test.ufo
Traceback (most recent call last):
  File "/home/nikolaus/.local/bin/UFObuildComp", line 9, in <module>
    load_entry_point('pysilfont==1.1.2', 'console_scripts', 'UFObuildComp')()
  File "build/bdist.linux-x86_64/egg/silfont/scripts/UFObuildComp.py", line 229, in cmd
  File "build/bdist.linux-x86_64/egg/silfont/core.py", line 501, in execute
  File "build/bdist.linux-x86_64/egg/silfont/scripts/UFObuildComp.py", line 143, in doit
ValueError: invalid literal for int() with base 10: '245.0'
```

The bug can be worked around by normalizing the UFO, but proper handling would be more desirable :)

**Comment by DavidRaymond** [comment]
We'll fix that.
I think just using int(float()) should work.  Do we need to warn if rounding occurs?  Not sure!

**Comment by madig** [comment]
Components can't be placed at floating point coordinates?

**Comment by jvgaultney** [comment]
Why would you want to put a component at a location defined with floating point coordinates? Can you give an example? (What I'm saying is that while such may be possible in the spec, supporting it is probably a very low priority unless you can make a good argument of why it's needed.)

**Comment by madig** [comment]
I don't, I just suggested it to avoid thinking about rounding ;)

**Comment by DavidRaymond** [comment]
Fixed in https://github.com/silnrsi/pysilfont/commit/4f6080cdb856efa743fd2e7d1f954478fe2a5908
