### ISSUE TITLE
psfcreateinstances output won't compile

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#61]
The Lateef master UFO can be converted to a TTF using psfufo2ttf, but when I use psfcreateinstances to generate an instance UFO, psfufo2ttf abends when trying to convert the instance UFO:

```
vagrant@smith-xenial:/smith/font-lateef$ cd source
vagrant@smith-xenial:/smith/font-lateef/source$ ppsfufo2ttf Lateef-Regular.ufo/ x.ttf
2019-03-20 00:04:16 Progress: Converting UFO to ttf without OT
2019-03-20 00:04:49 Progress: Saving ttf file
2019-03-20 00:04:51 Progress: Done
2019-03-20 00:04:51 Progress: Command completed with no warnings

vagrant@smith-xenial:/smith/font-lateef/source$ psfcreateinstances lateef.designspace
2019-03-20 00:09:12 Progress: Opening log file for output: /smith/font-lateef/source/lateef_createinstances.log
2019-03-20 00:09:12 Progress: Interpolating master UFOs from designspace
2019-03-20 00:10:03 Progress: Done
2019-03-20 00:10:04 Progress: Command completed with 0 errors and 1 warnings
2019-03-20 00:10:04 Progress: See log file for warning messages or rerun with '-p scrlevel=w'
vagrant@smith-xenial:/smith/font-lateef/source$ cd instances
vagrant@smith-xenial:/smith/font-lateef/source/instances$ psfufo2ttf Lateef-Regular.ufo/ x.ttf
2019-03-20 00:10:32 Progress: Converting UFO to ttf without OT
Traceback (most recent call last):
  File "/usr/bin/psfufo2ttf", line 9, in <module>
    load_entry_point('pysilfont==1.4.2.dev0', 'console_scripts', 'psfufo2ttf')()
  File "/usr/lib/python2.7/dist-packages/silfont/scripts/psfufo2ttf.py", line 69, in cmd
    def cmd(): execute(None, doit, argspec)
  File "/usr/lib/python2.7/dist-packages/silfont/core.py", line 560, in execute
    newfont = fn(args)
  File "/usr/lib/python2.7/dist-packages/silfont/scripts/psfufo2ttf.py", line 47, in doit
    glyphSet = preProcessor.process()
  File "/usr/lib/python2.7/dist-packages/ufo2ft/preProcessor.py", line 50, in process
    func(ufo, glyphSet)
  File "/usr/lib/python2.7/dist-packages/ufo2ft/filters/cubicToQuadratic.py", line 45, in __call__
    modified = super(CubicToQuadraticFilter, self).__call__(font, glyphSet)
  File "/usr/lib/python2.7/dist-packages/ufo2ft/filters/__init__.py", line 200, in __call__
    context = self.set_context(font, glyphSet)
  File "/usr/lib/python2.7/dist-packages/ufo2ft/filters/cubicToQuadratic.py", line 26, in set_context
    ctx.absoluteError = relativeError * font.info.unitsPerEm
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
vagrant@smith-xenial:/smith/font-lateef/source/instances$
```

The one warning from psfcreateinstances was for "Possibly missing unicodes for 541 glyphs: "

I'm searching for substantive differences in the UFOs, the biggest differences seems to be in fontinfo.plist. All the .glif files are identical in content but not in form (e.g., some use ' others ", some points are in different order, etc.)

Will continue researching difference, but if anyone has ideas about the traceback please chime in.

**Comment by anthrotype** [comment]
By reading the traceback, the TypeError exception seems to be triggered by font.info.unitsPerEm being None.
That is a required attribute for processing UFOs with ufo2ft.

**Comment by bobh0303** [comment]
weird. Thanks for spotting that unisPerEm was missing, but it isn't the thing missing. Something is going really with psfcreateinstances. If I try to normalize the resulting instance, the log includes:
```
Required fields missing from fontinfo.plist: [u'ascender', u'copyright', u'descender', u'openTypeNameManufacturer', u'unitsPerEm', u'versionMajor', u'versionMinor']
capHeight is missing from fontinfo.plist
copyright is missing from fontinfo.plist
openTypeNameDescription is missing from fontinfo.plist
openTypeNameDesigner is missing from fontinfo.plist
openTypeNameDesignerURL is missing from fontinfo.plist
openTypeNameLicense is missing from fontinfo.plist
openTypeNameLicenseURL is missing from fontinfo.plist
openTypeNameManufacturerURL is missing from fontinfo.plist
openTypeNameSampleText is missing from fontinfo.plist
openTypeOS2CodePageRanges is missing from fontinfo.plist
openTypeOS2UnicodeRanges is missing from fontinfo.plist
openTypeOS2VendorID is missing from fontinfo.plist
openTypeOS2WeightClass is missing from fontinfo.plist
openTypeOS2WidthClass would be added  New value: 5
xHeight would be added  New value: 599
openTypeNameUniqueID would be added  New value: Dummy: Lateef Regula...
openTypeNameVersion would be added  New value: Version 999.999
openTypeOS2WeightClass would be added  New value: 400
openTypeHheaLineGap would be added  New value: 0
openTypeOS2WinDescent would be added  New value: -999
openTypeOS2TypoLineGap would be added  New value: 0
openTypeOS2Type would be added  New value: []
openTypeHheaDescender would be added  New value: 999
openTypeOS2TypoDescender would be added  New value: 999
openTypeOS2WinAscent would be added  New value: 999
openTypeNamePreferredFamilyName would be added  New value: Lateef
openTypeHheaAscender would be added  New value: 999
openTypeNamePreferredSubfamilyName would be added  New value: Regular
openTypeOS2TypoAscender would be added  New value: 999
```

**Comment by bobh0303** [comment]
Follow-up. Just getting back to this and it is still a problem. Example:

For LateefLight-Regular (at the same coordinates as masters/Lateef-Light) `psfcreateinstance` creates the following extremely truncated fontinfo.plist:
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>familyName</key>
    <string>Lateef Light</string>
    <key>guidelines</key>
    <array/>
    <key>postscriptBlueValues</key>
    <array/>
    <key>postscriptFamilyBlues</key>
    <array/>
    <key>postscriptFamilyOtherBlues</key>
    <array/>
    <key>postscriptFontName</key>
    <string>LateefLight-Regular</string>
    <key>postscriptOtherBlues</key>
    <array/>
    <key>postscriptStemSnapH</key>
    <array/>
    <key>postscriptStemSnapV</key>
    <array/>
    <key>styleMapFamilyName</key>
    <string>Lateef Light</string>
    <key>styleMapStyleName</key>
    <string>regular</string>
    <key>styleName</key>
    <string>Regular</string>
  </dict>
</plist>
```
Other than empty arrays in the guidelines and postscript stuff, the only things in here are 5 attributes from the designspace instance ( `familyName`, `postscriptFontName`,  `stylemapFamilyName`, `styleMapStyleName`, `styleName`).  

Can something in the masters cause this? 
@nrsiward @jvgaultney Any ideas?

**Comment by bobh0303** [comment]
See 56341285984b1f5452f005daebe1a1e26f5c410a for simplified demonstration.

**Comment by mhosken** [comment]
<instance> elements really require <info/> and <kerning/> without them, all the goodies from the fontinfo.plist don't get copied into instances, only the rebuilt values.

**Comment by bobh0303** [comment]
That fixes it. Thanks.
