### ISSUE TITLE
psfnormalize aborts if there is no guidelines element in fontinfo.plist

### ISSUE THREAD

**Issue by devosb** [silnrsi/pysilfont#76]
In [Bailey](https://github.com/nlci/mlym-font-bailey), I use `fontforge` to [convert](https://github.com/nlci/mlym-font-bailey/blob/master/tools/archive/sfd2ufo.bash) from SFD to UFO. Previously (many months ago) a `guidelines` element would be generated in fontinfo.plist, but with no `string` or `integer` value following it. A newer build of fontforge does not produce the `guidelines` element. A diff (the font name gets renamed, which is why the diff shows Rachana and the final font is Bailey) shows
```
diff new/Rachana-Regular.ufo/fontinfo.plist old/Rachana-Regular.ufo/fontinfo.plist
139a140
>     <key>guidelines</key>
```
With the old `fontforge` output, `psfnormalize` runs fine, and [removes](https://github.com/nlci/mlym-font-bailey/blob/master/source/Bailey-Regular.ufo/fontinfo.plist) the `guidelines` element, presumably since there is no value associated with it. With the new `fontforge` output, `psfnormalize -p backup=0 -v 3 -p checkfix=none Rachana-Regular.ufo` aborts with
```
2022-06-17 10:54:21 Progress: Reading UFO: Rachana-Regular.ufo
Traceback (most recent call last):
  File "/home/bobby/.local/bin/psfnormalize", line 8, in <module>
    sys.exit(cmd())
  File "/home/bobby/.local/lib/python3.10/site-packages/silfont/scripts/psfnormalize.py", line 30, in cmd
    def cmd() : execute("UFO",doit, argspec)
  File "/home/bobby/.local/lib/python3.10/site-packages/silfont/core.py", line 633, in execute
    if tool == "UFO": aval = Ufont(aval, params=params)
  File "/home/bobby/.local/lib/python3.10/site-packages/silfont/ufo.py", line 297, in __init__
    if "fontinfo.plist" in self.dtree: self.fontinfo = self._readPlist("fontinfo.plist")
  File "/home/bobby/.local/lib/python3.10/site-packages/silfont/ufo.py", line 610, in _readPlist
    plist = Uplist(font=self, filen=filen)
  File "/home/bobby/.local/lib/python3.10/site-packages/silfont/ufo.py", line 821, in __init__
    if filen and dirn: self.populate_dict()
  File "/home/bobby/.local/lib/python3.10/site-packages/silfont/ufo.py", line 829, in populate_dict
    self._contents[key] = [pl[i], pl[i + 1]]  # The two elements for the item
IndexError: child index out of range
```
Test data (with two UFOs, one old, one new) is attached.
[guidelines.zip](https://github.com/silnrsi/pysilfont/files/8929447/guidelines.zip)

**Comment by devosb** [comment]
Now I see that the omission of the `<key>guidelines</key>` line leaves an `<array/>` element that does not correspond to a key in the plist, which `psfnormalize` does not expect. Probably the [same issue](https://github.com/fontforge/fontforge/issues/4951) that has already been reported to FontForge.
