### ISSUE TITLE
psfufo2ttf crashes if UFO includes public.unicodeVariationSequences

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#84]
Padauk is a font that includes Unicode variation sequences in the `lib.plist` files. It currently includes those in the `org.sil.variationSequences` key which is processed by `psfufo2ttf` using our own custom code.

The UFO spec now defines an official structure in lib.plist, [public.unicodeVariationSequences](https://unifiedfontobject.org/versions/ufo3/lib.plist/#publicunicodevariationsequences), which, [according to Denis Moyogo Jacquerye](https://typedrawers.com/discussion/comment/63483/#Comment_63483), is supported in `fontmake` and `ufo2ft`.  

The structures of the two keys is identical, so we should be able to just rename it in the UFOs, so I decided to try it out.

After renaming the keys in the two master UFOs I compiled one of them with a simple `fontmake` command and confirmed that it generated the appropriate Variation Selector (0,5,14) cmap and its content (as displayed by OTM) was identical to that of a recently built Padauk.

Unfortunately trying to build the font package with smith now causes `psfufo2ttf` to traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/psfufo2ttf", line 8, in <module>
    sys.exit(cmd())
  File "/usr/local/lib/python3.10/dist-packages/silfont/scripts/psfufo2ttf.py", line 119, in cmd
    def cmd(): execute(None, doit, argspec)
  File "/usr/local/lib/python3.10/dist-packages/silfont/core.py", line 647, in execute
    newfont = fn(args)
  File "/usr/local/lib/python3.10/dist-packages/silfont/scripts/psfufo2ttf.py", line 94, in doit
    font.save(args.ottf)
  File "/usr/local/lib/python3.10/dist-packages/fontTools/ttLib/ttFont.py", line 212, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/lib/python3.10/dist-packages/fontTools/ttLib/ttFont.py", line 259, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python3.10/dist-packages/fontTools/ttLib/ttFont.py", line 710, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python3.10/dist-packages/fontTools/ttLib/ttFont.py", line 732, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python3.10/dist-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 193, in compile
    self.tables.sort()  # sort according to the spec; see CmapSubtable.__lt__()
  File "/usr/local/lib/python3.10/dist-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 369, in __lt__
    return selfTuple < otherTuple
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by bobh0303** [comment]
I just tried this script:
```
from defcon import Font
from ufo2ft import compileTTF
ufo = Font('Padauk-Regular.ufo')
ttf = compileTTF(ufo)
ttf.save('from_ufo2ft.ttf')
```
and it also generated a ttf containing a correct Variation Sequences cmap.

**Comment by bobh0303** [comment]
Excerpts from `psfversion` in case useful:
```
Pysilfont Copyright (c) 2014-2023 SIL International (https://www.sil.org)

   Version:           1.6.1.dev10
   Commands in:       /usr/local/bin/
   Code running from: /usr/local/lib/python3.10/dist-packages/silfont
   using:             Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

defcon:              0.10.4.dev2+g32c956c /usr/local/lib/python3.10/dist-packages/defcon
fontParts:           0.11.1.dev13+gaa43bdb /usr/local/lib/python3.10/dist-packages/fontParts
fontTools:           4.42.2.dev0     /usr/local/lib/python3.10/dist-packages/fontTools
ufo2ft:              2.33.4          /usr/local/lib/python3.10/dist-packages/ufo2ft
ufoLib2:             0.16.0          /usr/local/lib/python3.10/dist-packages/ufoLib2
```

**Comment by bobh0303** [comment]
It turns out that `psfufo2ttf` can get UVS data from two different places. The logic can be summarized:

> IF key `org.sil.variationSequences` is present in `lib.plist`
>    then read and parse the data therein and use that to build a UVS cmap
> ELSE IF there are `.glif` files containing `org.sil.uvs`
>    then read and parse the data therein, accumulating info from all `.glif` files, then use that data to build a UVS cmap.
> ELSE
>     don't build a UVS cmap.

In other words, `psfufo2ttf` uses _either_ the `lib.plist` info _or_ the `.glif` info, but not both... preferring the `lib.plist` info.

For reasons I don't understand (but probably historical accident), Padauk has _both_ `org.sil.variationSequences` (in the `lib.plist`) _and_ `org.sil.uvs` in a number of `.glif` files. _And the data is different:_ 

`lib.plist`:
![image](https://github.com/silnrsi/pysilfont/assets/6842108/1c632f5a-a414-48e8-8c2e-20c1ade13c02)

`.glif`:
![image](https://github.com/silnrsi/pysilfont/assets/6842108/bd00bcfd-b776-464a-9539-5087064dd10d)

Note that the `.glif` info is actually invalid as it has multiple entries _for the same UVS_, e.g.
![image](https://github.com/silnrsi/pysilfont/assets/6842108/0b1c7378-7aed-4c8f-9f28-b4208933ca7b)
and
![image](https://github.com/silnrsi/pysilfont/assets/6842108/a2c63a1e-10dd-403d-b25a-c9ee7bd2e77e)

The first conclusion to be made is that the UVS data in the `.glif` files in Padauk should be removed since (a) it isn't being used anyway and (b) it looks to be incorrect.

**Comment by bobh0303** [comment]
As to the `psfufo2ttf` crash, if we:

- rename `org.sil.variationSequences` in lib.plist to `public.unicodeVariationSequences`, AND
- remove `org.sil.uvs` data from all `.glif` files that have it

then `psfufo2tt2` succeeds.

No one should ever do this, but:

If _both_ `org.sil.variationSequences` and `public.unicodeVariationSequences` are in `lib.plist`, the same traceback occurs.  This suggests two things:

1. fontTools fails if _any_ UVS information is added to the cmap prior to its own processing of `public.unicodeVariationSequences`
2. We should enhance `psfufo2ttf` to defend against this by ensuring we don't add any UVS info if `public.unicodeVariationSequences` is present.
